# Set the planning mode of the robot to use in planner.
# ROS 2 requires UPPER_SNAKE_CASE constant names (ROS 1 was kManual/kAuto).
int32 K_MANUAL = 0
int32 K_AUTO = 1
# Can only be used with one of above values. Check Params/BoundModeType for more details.
int32 planning_mode
---
bool success
