"""Reusable mission stage decision helpers."""

from __future__ import annotations

from navlab.common.companion.mission.stages.hover import (
    HoverDecision,
    HoverHealthGateConfig,
    HoverHealthGateResult,
    HoverHoldConfig,
    HoverHoldStage,
    HoverInputs,
    HoverRequirements,
    apply_hover_health_gate,
    capture_hold_anchor,
    classify_hover_health,
    decide_hover,
    height_reaches_target,
    hold_axis_or_current,
    hold_yaw_or_current,
    hover_health_payload,
    hover_hold_setpoint_axes,
    hover_inputs_from_context,
    independent_takeoff_height_reached,
    should_fail_fast_wait_ready,
    should_send_position_hold_setpoint,
)
from navlab.common.companion.mission.stages.landing import (
    FCU_LAND_PARAM_NAMES,
    LANDING_POLICY_AP_LAND_MODE_AFTER_HOVER,
    LANDING_POLICY_GUIDED_DESCENT,
    LANDING_POLICY_LAND_IN_PLACE,
    LandingStage,
    LandingStageConfig,
    fcu_land_params_report,
    landing_acceptance_ok,
    landing_controller_for_state,
    landing_descent_profile_enforced,
    landing_handoff_confirmed,
    landing_policy_uses_ap_land_mode,
    should_command_land_this_tick,
    should_send_disarm_after_touchdown,
    should_use_guided_descent_before_land,
)
from navlab.common.companion.mission.stages.prefix import (
    ArmStage,
    FlightPrefixConfig,
    GuidedModeStage,
    RuntimeReadyStage,
    TakeoffStage,
)

__all__ = [
    "ArmStage",
    "FCU_LAND_PARAM_NAMES",
    "FlightPrefixConfig",
    "GuidedModeStage",
    "HoverDecision",
    "HoverHealthGateConfig",
    "HoverHealthGateResult",
    "HoverHoldConfig",
    "HoverHoldStage",
    "HoverInputs",
    "HoverRequirements",
    "LANDING_POLICY_AP_LAND_MODE_AFTER_HOVER",
    "LANDING_POLICY_GUIDED_DESCENT",
    "LANDING_POLICY_LAND_IN_PLACE",
    "LandingStage",
    "LandingStageConfig",
    "RuntimeReadyStage",
    "TakeoffStage",
    "apply_hover_health_gate",
    "capture_hold_anchor",
    "classify_hover_health",
    "decide_hover",
    "fcu_land_params_report",
    "height_reaches_target",
    "hold_axis_or_current",
    "hold_yaw_or_current",
    "hover_health_payload",
    "hover_hold_setpoint_axes",
    "hover_inputs_from_context",
    "independent_takeoff_height_reached",
    "landing_acceptance_ok",
    "landing_controller_for_state",
    "landing_descent_profile_enforced",
    "landing_handoff_confirmed",
    "landing_policy_uses_ap_land_mode",
    "should_command_land_this_tick",
    "should_fail_fast_wait_ready",
    "should_send_disarm_after_touchdown",
    "should_send_position_hold_setpoint",
    "should_use_guided_descent_before_land",
]
